---
title: "report"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

The written report produced by your team is central to this project. This will detail how you completed your project, and should cover data collection and cleaning, exploratory analyses, alternative strategies, descriptions of approaches, and a discussion of results. We anticipate that your project will change somewhat over time; these changes and the reasons for them should be documented! You will write one report document per group, and be sure to include all group member names in the document.


Motivation: Provide an overview of the project goals and motivation.

* Studying at Columbia University, except enjoying fascinating school life, we should always be concerned about the safety problem. Frequent email alerts, Citizen apps popping up, and terrifying news, they are all reminding us that there are many underlying unsafe factors around us. The New York government has made a public crime map at https://maps.nyc.gov/crime/.
The information in it, however, is way too redundant for a student as we are more concerned about the safety conditions around our campus and our places of residence. Luckily, NYPD has posted the up-to-date dataset that includes all valid felony, misdemeanor, and violation crimes reported to the New York City Police Department, and it includes more information that we are interested in, for example, the time of occurrence of the complaint, the victim’s statistics. After analyzing the dataset, we can have a more comprehensive understanding about the crimes around us. Finally, we want to draw a fine map locating the crime incidents around our campus, informing us what time may be more dangerous and we can avoid activities at that time. The map will give students the option of looking up when they go outside most often to help them more accurately determine the likelihood of danger. We also want this result to help all the staff and students in Columbia University have an opportunity to evaluate the risk, avoid the danger, and allow them to access crime rates in the areas they care about to keep themselves safe.

Related work: 




What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis?



Data: 

* The data is from NYC Opendata, https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Current-Year-To-Date-/5uac-w243.This dataset is provided by NYPD, and is recently updated on Oct.19th. This dataset have 81.4K views and 16.7 downloads. Therefore, this dataset is expected to be accurate, authoritative, prompt and worth analyzing. 
* Since the main purpose of this product is to help all the staff and students in Columbia University, so we decide to let our map cover the Manhattan area, and in order to give them most meaningful results, we focus the year after 2010. Then, we do the fowllowing: 1. select the rows recording date later than 2010-01-01. 2. Select the borogh as Manhattan. 3. select the variables we are interseted in. 4. filter the latitude and longitude to limit it around columbia campus (roughly). The latitude range is approximately from 86 street subway station to George Washing Bridge (West 178th street). The longitude range is from Hudson river to Harlem river and Central park. This region covers Columbia University campus (and CUIMC) and the neighborhood area. You could find details here: [Data cleaning](code/data import and cleaning.Rmd)
* We use the following items to do our project:

  *`id`: case id numbers.
  
  *`bor0`: Manhattan area.
  
  *`year`: The year this specific case happened.
  
  *`month`: The month this specific case happened.
  
  *`day`: The day this specific case happened.
  
  *`hour`: The exact hour this specific case happened.
  
  *`minute`: The exact minute this specific case happened.
  
  *`second`: The exact second this specific case happened.
  
  *`success_fail`: Indicator of whether crime was successfully completed or attempted, but failed or was interrupted prematurely.
  
  *`level`: Level of offense: felony, misdemeanor, violation.
  
  *`description`: Description of offense corresponding with key code.
  
  *`location`: Specific location of occurrence in or around the premises; inside, opposite of, front of, rear of.
  
  *`susp_age`: the age of suspect.
  
  *`susp_race`: the race of suspect.
  
  *`susp_sex`: the sex of suspect.
  
  *`vic_age`: the age of victim.
  
  *`vic_race`: the race of victim.
  
  *`vic_sex`: the sex of victim.
  
  *`logitude`: Logitude at Global Coordinate System.
  
  *`latitude`: Latitude at Global Coordinate System.
   




Exploratory analysis: Visualizations, summaries, and exploratory statistical analyses. Justify the steps you took, and show any major changes to your ideas.


Additional analysis: If you undertake formal statistical analyses, describe these in detail
Discussion: What were your findings? Are they what you expect? What insights into the data can you make?



