---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)

cu_df = read_csv("../data/full_filter_data.csv")
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
Year0 = cu_df %>% distinct(year) 
Year1 = arrange(Year0, desc(year))

selectInput(
  inputId = 'year_choice',
  label = h3('Year Choice'),
  choices = Year1,
  selected = '2022'
)

Month0 = cu_df %>% distinct(month) 
Month1 = arrange(Month0, month)

selectInput(
  inputId = 'month_choice',
  label = h3('Month Choice'),
  choices = Month1,
  selected = '1'
)

Day0 = cu_df %>% distinct(day) 
Day1 = arrange(Day0, day)

selectInput(
  inputId = 'day_choice',
  label = h3('Day Choice'),
  choices = Day1,
  selected = '1'
)

sliderInput(
  inputId = 'hour_range',
  label = h3('Hour Range'),
  min = 0, max = 24, value = c(8, 18)
)

Level = cu_df %>% distinct(level) %>% pull()

radioButtons(
  inputId = 'level_choice',
  label = h3('Crime Level'),
  choices = Level,
  selected = 'VIOLATION'
)
```


Column 
-----------------------------------------------------------------------

### Safety Map around Columbia University

```{r}
renderPlotly({
  cu_df %>% 
    filter(
      year == input[['year_choice']],
      month == input[['month_choice']],
      day == input[['day_choice']],
      hour >= input[['hour_range']][1],
      hour <= input[['hour_range']][2],
    ) %>% 
    plot_ly(x = ~latitude, y = ~longitude, color = "red",
            type = 'scatter', mode = 'makers', alpha = .5)
})
```

renderPlotly({
  nyc_airbnb %>% 
    filter(borough == input[['borough_choice']],
           price >= input[['price_range']][1],
           price <= input[['price_range']][2],
           room_type == input[['room_choice']]) %>% 
    plot_ly(x = ~lat, y = ~long, color = ~price,
           type = 'scatter', mode = 'markers', alpha = .5)
})